[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "mj_tools"
version = "0.1.0"
description = "A toolbox for listing information of generated images in MidJourney."

authors = [
    { name = "Michael Steffen", email = "miyels@proton.me" }
]

license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11"
keywords = ["midjourney", "images", "metadata", "extracting", "crawling"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
"Documentation" = "https://github.com/msmiyels/projects-mj_hackz#readme"
"Source Code" = "https://github.com/msmiyels/projects-mj_hackz"
"Bug Tracker" = "https://github.com/msmiyels/projects-mj_hackz/issues"

[tool.uv]
default-groups = ["dependencies", "dev"]

[dependency-groups]
dependencies = [
    "google-api-python-client>=2.0.0",
    "google-generativeai>=0.8.0",
    "pandas>=2.2.3",
    "pillow>=10.3.0",
    "requests>=2.0.0",
    "python-dotenv>=1.0.0",
    { path = "src/python/mj_tools", develop="true" }
]

dev = [
    "pytest>=8.3.0",
    "flake8>=4.0.0"
]
